repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.276
    hooks:
    -   id: ruff
        args: [--fix]
-   repo: https://github.com/google/yapf
    rev: v0.33.0
    hooks:
    -   id: yapf
        # run recursively, in-place, in parallel, style defined in pyproject.toml
        args: [-r, -i, -p, --style pyproject.toml]
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort