name: pre-commit

on:
  push:
    branches: '*'
  pull_request:
    branches: [ master ]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Pre-commit
        uses: pre-commit/action@v3.0.0
